# We use kramdown for TOC generation.
# See http://www.seanbuscay.com/blog/jekyll-toc-markdown for details:
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Monix
tagline:          'Asynchronous Programming for Scala & Scala.js'
description:      'Scala/Scala.js library for composing asynchronous, event-based programs.'
url:              https://monix.io
baseurl:          /

author:
  name:           'Alexandru Nedelcu'
  url:            https://twitter.com/alexelcu

permalink:     "/blog/:categories/:year/:month/:day/:title"
paginate_path: "/blog/page:num/"
paginate:      5

# Custom vars
version:          1.2
beta_version:     2.0-RC2

github:
  repo:           https://github.com/monixio/monix

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
